import { Link } from '@tanstack/react-router';
import { Header, Footer, Reveal, Button, ArrowUpRight, ArrowRight, Check } from './elements';

export default function CaseStudiesPage() {
  return (
    <div className="site-shell">
      <Header />
      
      {/* Hero */}
      <section className="section py-20 border-b border-border text-center">
        <div className="max-w-4xl mx-auto px-6">
          <span className="eyebrow tracking-widest text-xs font-semibold text-primary uppercase block mb-4">
            PERFORMANCE & ATTRIBUTION
          </span>
          <h1 className="text-4xl sm:text-6xl font-display font-medium text-foreground leading-tight tracking-tight mb-6">
            Real Proof. Transparent Attribution.
          </h1>
          <p className="text-lg sm:text-xl text-muted-foreground leading-relaxed max-w-2xl mx-auto mb-8 font-sans">
            How forward-thinking direct-to-consumer and gifting brands measure the concrete financial returns of their physical packaging insertions.
          </p>
        </div>
      </section>

      {/* Attribution Methodology Notice */}
      <section className="py-12 bg-primary/5 border-b border-border">
        <div className="max-w-5xl mx-auto px-6">
          <div className="grid md:grid-cols-2 gap-8 items-center">
            <div>
              <span className="text-xs uppercase font-semibold text-primary tracking-wider block mb-2">
                MEASUREMENT INTEGRITY
              </span>
              <h2 className="text-2xl font-display font-medium text-foreground mb-3">
                How AVIRA Separates Attributed vs Incremental Revenue
              </h2>
              <p className="text-sm text-muted-foreground font-sans leading-relaxed">
                We believe in rigorous financial reporting. AVIRA does not inflate performance by claiming organic sales. We clearly differentiate between actions triggered directly by packaging inserts and baseline customer repurchases.
              </p>
            </div>
            <div className="space-y-4">
              <div className="p-4 rounded-lg bg-paper border border-border">
                <strong className="text-sm font-semibold text-foreground block mb-1">
                  1. Attributed Revenue
                </strong>
                <p className="text-xs text-muted-foreground font-sans">
                  Revenue generated by transactions where a unique, single-use AVIRA unboxing coupon or referral link was directly redeemed at checkout.
                </p>
              </div>
              <div className="p-4 rounded-lg bg-paper border border-border">
                <strong className="text-sm font-semibold text-foreground block mb-1">
                  2. Incremental Revenue
                </strong>
                <p className="text-xs text-muted-foreground font-sans">
                  The net revenue lift measured when comparing cohorts receiving AVIRA smart inserts against an unengaged control cohort over 30, 60, and 90-day intervals.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Illustrative Benchmark Study */}
      <section className="section py-20 border-b border-border">
        <div className="max-w-6xl mx-auto px-6">
          <div className="p-8 sm:p-12 rounded-lg border border-border bg-paper/60">
            <div className="flex flex-wrap items-center justify-between gap-4 mb-8 pb-6 border-b border-border">
              <div>
                <span className="text-xs uppercase text-primary font-semibold tracking-wider block mb-1">
                  ILLUSTRATIVE CAMPAIGN STUDY
                </span>
                <h3 className="text-3xl font-display font-medium text-foreground">
                  LIVIQUE — Botanical Skincare
                </h3>
              </div>
              <span className="px-3 py-1 rounded-full text-xs font-semibold bg-primary/10 text-primary border border-primary/20">
                Direct-to-Consumer / Skincare
              </span>
            </div>

            <div className="grid md:grid-cols-4 gap-6 mb-8 text-center">
              <div className="p-4 rounded border border-border bg-background">
                <span className="text-3xl font-display font-bold text-primary block">5,000</span>
                <span className="text-xs text-muted-foreground uppercase font-sans">Delivered Orders</span>
              </div>
              <div className="p-4 rounded border border-border bg-background">
                <span className="text-3xl font-display font-bold text-primary block">2,184</span>
                <span className="text-xs text-muted-foreground uppercase font-sans">Card Scans (43.6%)</span>
              </div>
              <div className="p-4 rounded border border-border bg-background">
                <span className="text-3xl font-display font-bold text-primary block">312</span>
                <span className="text-xs text-muted-foreground uppercase font-sans">UGC Submissions</span>
              </div>
              <div className="p-4 rounded border border-border bg-background">
                <span className="text-3xl font-display font-bold text-primary block">₹2,86,400</span>
                <span className="text-xs text-muted-foreground uppercase font-sans">Attributed Revenue</span>
              </div>
            </div>

            <div className="space-y-4 text-sm text-muted-foreground font-sans leading-relaxed">
              <p>
                <strong>The Challenge:</strong> High Meta CAC required Livique to extract maximum value from existing shipments. Follow-up emails for review collection yielded sub-1% response rates.
              </p>
              <p>
                <strong>The Implementation:</strong> Livique placed a botanical-styled QR insert card into every 30ml serum mailer, offering a ₹150 second-order voucher in exchange for an unboxing video or peer referral.
              </p>
              <p>
                <strong>The Result:</strong> 43.6% of delivered customers scanned the QR code. Within 14 days, 143 repeat orders were generated, unlocking ₹2,86,400 in direct attributed revenue and 312 rights-cleared customer video clips.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="final-cta py-24 text-center">
        <span className="eyebrow block mb-3">SEE YOUR PROJECTED METRICS</span>
        <h2 className="text-3xl sm:text-5xl font-display font-medium mb-6">
          Calculate your post-purchase revenue potential.
        </h2>
        <Button variant="ivory" asChild size="lg">
          <Link to="/start-free">Start Free Pilot <ArrowUpRight className="ml-2 h-4 w-4" /></Link>
        </Button>
      </section>

      <Footer />
    </div>
  );
}
