import { useEffect, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, ArrowRight, Menu, X, ScanLine, Check, Gift, Copy, Camera, Users, Star, Package } from 'lucide-react';
import QRCode from 'qrcode';
import { Button } from '@/components/ui/button';
import packageImage from '@/assets/final_product.png';
import customerImage from '@/assets/customer.jpg';
import logoWhite from '@/assets/avira-logo-white.png';
import logoDark from '@/assets/avira-logo-dark.png';
import { reward } from '@/lib/product';
export { Button, packageImage, customerImage, ArrowUpRight, ArrowRight, ScanLine, Check, Gift, Copy, Camera, Users, Star, Package };
export function Brand({ dark = false }) { return <Link to="/" className="brand" aria-label="AVIRA"><img src={dark ? logoWhite : logoDark} alt="AVIRA — Every Order A Lasting Connection" className="brand-logo-img" /></Link>; }
export function Header({dark=false}) { const [open,setOpen]=useState(false); return <header className={`site-header ${dark?'header-dark':''}`}><Brand dark={dark}/><nav className={open?'navigation is-open':'navigation'}><a href="/#product" onClick={()=>setOpen(false)}>Product</a><Link to="/templates" onClick={()=>setOpen(false)}>Box Templates</Link><a href="/#how-it-works" onClick={()=>setOpen(false)}>How it works</a><a href="/#for-brands" onClick={()=>setOpen(false)}>For brands</a><a href="/#pricing" onClick={()=>setOpen(false)}>Pricing</a></nav><div className="nav-actions"><Link to="/demo" className="login-link">Explore demo</Link><Button variant={dark?'ivory':'default'} asChild><Link to="/start-free">Start Free <ArrowUpRight/></Link></Button><Button className="mobile-menu" variant="ghost" size="icon" aria-label={open?'Close menu':'Open menu'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div></header>; }
export function Reveal({children,className=''}) { const reduce=useReducedMotion(); return <motion.div className={className} initial={reduce?false:{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.7}}>{children}</motion.div>; }
export function QR({className=''}) { const [src,setSrc]=useState(''); useEffect(()=>{ QRCode.toDataURL(`${window.location.origin}/demo`,{margin:0,width:180,color:{dark:'#304A3A',light:'#F4EFE6'}}).then(setSrc); },[]); return <div className={`qr-code ${className}`}>{src?<img src={src} width="180" height="180" alt="Scan to explore AVIRA"/>:<ScanLine size={80}/>}</div>; }
export function QRCard({flip=false}) { const [back,setBack]=useState(true); return <div className={`physical-card ${flip?'interactive-card':''}`}><span className="eyebrow">AVIRA / A LITTLE SOMETHING EXTRA</span><h3>{back?'Your order unlocked a reward.':'Thank you for shopping with us.'}</h3>{back?<QR/>:<Gift size={70}/>}<span className="card-foot">SCAN · PARTICIPATE · UNLOCK</span>{flip&&<Button variant="link" onClick={()=>setBack(!back)}>Turn card over <ArrowRight/></Button>}</div>; }
export function RewardCard() { const [copied,setCopied]=useState(false); async function copy(){ try { await navigator.clipboard.writeText(reward.code); setCopied(true); } catch { setCopied(false); } } return <div className="reward-card"><span className="reward-seal"><Gift size={24}/></span><span className="eyebrow">A LITTLE THANK YOU</span><h3>Reward unlocked.</h3><div className="reward-amount">₹{reward.amount} <i>off</i></div><div className="coupon"><span>{reward.code}</span><Button variant="ghost" size="icon" aria-label="Copy reward code" onClick={copy}>{copied?<Check/>:<Copy/>}</Button></div><span className="reward-valid">{copied?'Code copied.':`Yours to enjoy. Valid for ${reward.validDays} days.`}</span></div>; }
export function Phone({onChoose,selected}) { return <div className="phone"><div className="phone-notch"/><div className="phone-brand">LIVIQUE <span>YOUR EVERYDAY, ELEVATED.</span></div><img src={customerImage} alt="Customer sharing their skincare ritual" width="768" height="1024" loading="lazy"/><div className="phone-content"><span className="eyebrow">GOOD THINGS DON'T END HERE</span><h3>Make it<br/>a little more yours.</h3><p>Choose how you'd like to engage.</p>{[{icon:Camera,name:'Share your experience',detail:'Earn loyalty points',action:'ugc'},{icon:Users,name:'Refer a friend',detail:'Earn a reward',action:'referral'},{icon:Star,name:'Leave an honest review',detail:'Help other shoppers',action:'review'}].map(({icon:Icon,name,detail,action})=><Button key={action} variant="experience" onClick={()=>onChoose?.(action)} className={selected===action?'selected':''}><Icon/><span>{name}<small>{detail}</small></span><ArrowUpRight/></Button>)}</div></div>; }
export function Footer(){ return <footer className="footer"><Brand/><div><a href="/#product">Product</a><Link to="/templates">Box Templates</Link><a href="/#how-it-works">How it works</a><a href="/#pricing">Pricing</a><a href="/#for-brands">For brands</a><Link to="/demo">Demo</Link></div><span>© 2026 AVIRA</span></footer>; }
export function Counter({value}) { const [n,setN]=useState(0); const reduce=useReducedMotion(); return <motion.span onViewportEnter={()=>{if(reduce){setN(value);return;} let start; const tick=(time)=>{start??=time;const p=Math.min((time-start)/1000,1);setN(Math.round(value*(1-(1-p)**3)));if(p<1)requestAnimationFrame(tick);};requestAnimationFrame(tick);}} viewport={{once:true}}>{n.toLocaleString('en-IN')}</motion.span>; }
