import { Link } from '@tanstack/react-router';
import { motion, useReducedMotion } from 'framer-motion';
import { Header, Footer, Reveal, QRCard, RewardCard, Phone, Counter, Button, packageImage, customerImage, ArrowUpRight, ArrowRight, ScanLine, Check, Camera, Users, Package } from './elements';
import { plans } from '@/lib/product';
const journey = [
 ['01 / THE ORDER','It starts with\nan order.','A new customer. A first impression. And the beginning of something bigger.','order'],
 ['02 / THE DELIVERY','The package\narrives.','An experience worth opening. With a little invitation tucked inside.','delivery'],
 ['03 / THE INVITATION','Small card.\nBig possibilities.','Your brand. Your message. One QR code that connects the physical to the digital.','qr'],
 ['04 / THE SCAN','A scan opens\na new chapter.','No app to download. No friction. Just a direct connection to your brand.','scan'],
 ['05 / THE EXPERIENCE','Let them make\nthe next move.','Share a moment. Bring a friend. Leave an honest review. Make engagement feel personal.','engage'],
 ['06 / THE REWARD','A little thanks.\nA reason to return.','Reward eligible content and referrals with something they’ll actually use.','reward'],
 ['07 / THE NEXT ORDER','One order\nbecomes another.','The first purchase isn’t the finish line. It’s the start of a lasting relationship.','repeat']
];
function OrderSlip({repeat=false}) {return <div className="order-slip"><div className="slip-brand">LIVIQUE</div><h4>{repeat?'Lovely to see you again.':'Good things are on their way.'}</h4><p>ORDER #{repeat?'LVQ-10235':'LVQ-10092'}</p><div className="slip-item"><img src={customerImage} alt="Botanical skincare serum" loading="lazy" width="768" height="1024"/><span><strong>The everyday ritual</strong>Botanical serum · 30 ml</span></div><div className="slip-total"><span>{repeat?'Reward applied':'Order total'}</span><strong>{repeat?'− ₹150':'₹1,299'}</strong></div><div className="slip-status"><Check size={13}/>{repeat?'Welcome back. Order confirmed.':'Order confirmed'}</div></div>;}
function StageVisual({type}){ if(type==='order')return <OrderSlip/>;if(type==='delivery')return <img className="stage-package" src={packageImage} alt="An open AVIRA package with a QR invitation inside" width="1024" height="1024" loading="lazy"/>;if(type==='qr')return <QRCard flip/>;if(type==='scan')return <><QRCard/><div className="scan-label"><ScanLine size={16}/>QR SCANNED <Check size={13}/></div></>;if(type==='engage')return <Phone/>;if(type==='reward')return <RewardCard/>;return <div className="repeat-visual"><img src={packageImage} alt="First order" width="1024" height="1024" loading="lazy"/><ArrowRight/><img src={packageImage} alt="A second order after redeeming a reward" width="1024" height="1024" loading="lazy"/></div>;}
export default function Home(){const reduce=useReducedMotion();return <div className="site-shell"><section className="hero"><Header dark/><div className="hero-main"><div className="hero-copy"><span className="eyebrow">THE DELIVERY IS JUST THE BEGINNING</span><h1>Turn every<br/>delivered order<br/>into your<br/><i>next customer.</i></h1><p>AVIRA turns packaging inserts into measurable customer engagement, UGC, referrals and repeat purchases.</p><div className="hero-ctas"><Button variant="ivory" asChild><Link to="/start-free">Start Free Pilot <ArrowUpRight/></Link></Button><a className="text-link" href="#how-it-works">See how it works <ArrowUpRight size={13}/></a></div></div><span className="hero-note">A small insert.<br/>An entirely new opportunity.</span><span className="hero-number">01<small> / 07</small></span><motion.img className="hero-image" src={packageImage} width="2752" height="1536" alt="Premium AVIRA gift box with a QR reward card" initial={reduce?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:1}}/><div className="floating-stat stat-scan"><small><ScanLine size={12}/> QR SCANNED</small><strong>2,184</strong><em>A connection, not just a delivery.</em></div><div className="floating-stat stat-ugc"><small><Camera size={12}/> UGC CREATED</small><strong>312 <span>↗</span></strong><em>Real people. Real stories.</em></div><div className="floating-stat stat-revenue"><small>ATTRIBUTED REVENUE</small><strong>₹2,86,400</strong><em>143 repeat orders. And counting.</em></div><div className="hero-bottom"><span><i className="status-dot"/>MADE FOR BRANDS THAT THINK BEYOND THE BOX.</span><span>ORDER → ENGAGE → REWARD → REPEAT <ArrowRight size={12}/></span></div></div></section><div className="trust-strip"><span>BUILT FOR THE NEXT GENERATION<br/>OF DIRECT-TO-CONSUMER BRANDS</span><span className="wordmark serif">LIVIQUE</span><span className="wordmark">FORM & FIELD</span><span className="wordmark serif">bloom & root</span><span className="wordmark">THE EVERYDAY CO.</span><span className="eyebrow">ILLUSTRATIVE BRANDS</span></div>
<section className="section problem" id="product"><Reveal className="section-heading"><span className="eyebrow">THE MISSED OPPORTUNITY</span><h2>Your relationship<br/>with the customer<br/>shouldn’t end<br/><i>at delivery.</i></h2></Reveal><Reveal className="problem-text"><div className="problem-mini"><Package size={32}/><span>ORDER</span><ArrowRight size={20}/><span>DELIVERED</span></div><p>Most brands spend heavily to acquire customers, then stop communicating once the package reaches their door.</p><strong>AVIRA changes what happens next. <ArrowUpRight size={14} className="inline"/></strong><div className="mt-5"><Button variant="lightOutline" asChild><Link to="/templates">Browse Gift Box Insert Card Templates <ArrowRight size={13}/></Link></Button></div></Reveal></section>
<section className="section journey" id="how-it-works"><div className="journey-intro"><Reveal className="section-heading"><span className="eyebrow">ONE ORDER. A WORLD OF POSSIBILITIES.</span><h2>Unbox your<br/><i>next chapter.</i></h2></Reveal><p>From the first checkout to the next purchase. Every moment, connected.</p></div>{journey.map(([number,title,text,type])=><div key={type} className="journey-stage"><Reveal className="stage-copy"><span className="stage-index">{number}</span><h3>{title.split('\n').map((line,i)=><span key={line}>{i>0&&<br/>}{line}</span>)}</h3><p>{text}</p>{type==='engage'&&<Button variant="link" asChild><Link to="/demo">Try the customer experience <ArrowUpRight/></Link></Button>}</Reveal><Reveal className="stage-visual"><StageVisual type={type}/></Reveal></div>)}</section>
<section className="section merchant"><Reveal className="section-heading"><span className="eyebrow">THE OTHER SIDE OF THE STORY</span><h2>While your<br/>customer gets<br/><i>rewarded…</i><br/>you get clarity.</h2><p>Every scan, every share, every return. See what your packaging is really bringing back.</p><Button variant="lightOutline" asChild className="mt-7"><Link to="/demo">See the merchant view <ArrowUpRight/></Link></Button></Reveal><Reveal className="analytics"><div className="analytics-head"><span>Beyond the delivery.</span><small>LIVE CAMPAIGN / LIVIQUE</small></div><div className="analytics-metrics">{[['Orders delivered',5000],['QR scans',2184],['UGC created',312],['Referrals',187],['Repeat orders',143],['Revenue attributed',286400]].map(([label,num])=><div key={label}><small>{label}</small><strong>{label==='Revenue attributed'?'₹':''}<Counter value={num}/></strong></div>)}</div><div className="funnel">{[['Orders',5000],['Scans',2184],['Engagements',824],['Rewards',611],['Coupon redemptions',204],['Repeat orders',143]].map(([name,num])=><div className="funnel-row" key={name}><span>{name}</span><Counter value={num}/></div>)}</div><p className="mt-5 text-xs text-muted-foreground">Illustrative campaign results.</p></Reveal></section>
<section className="section loop-section"><Reveal className="growth-loop"><div className="loop-center"><small>THE POST-PURCHASE LOOP</small>Good things<br/>come full circle.</div>{['ORDER','QR','ENGAGEMENT','UGC','REFERRAL','REWARD','REPEAT ORDER','NEW CUSTOMER'].map(n=><span className="loop-node" key={n}>{n}</span>)}</Reveal><Reveal className="section-heading"><span className="eyebrow">GROWTH THAT COMES BACK AROUND</span><h2>Not a one-off.<br/><i>A flywheel.</i></h2><p>Happy customers create content. Content brings new customers. Rewards bring them back. Your next order keeps the story going.</p></Reveal></section>
<section className="section brand-section" id="for-brands"><div className="brand-heading"><Reveal className="section-heading"><span className="eyebrow">FOR THE BRAND</span><h2>Your customers<br/>become <i>your marketing.</i></h2></Reveal><p>More authentic stories.<br/>Stronger relationships.<br/>Growth from within.</p></div><div className="brand-grid"><Reveal className="brand-feature feature-ugc"><img src={customerImage} alt="Real customer sharing a botanical skincare product" width="768" height="1024" loading="lazy"/><div className="feature-copy"><small>01 / USER-GENERATED CONTENT</small><h3>Real customers.<br/>Real stories.</h3></div></Reveal><Reveal className="brand-feature"><div className="referral-graphic"><span className="avatar-disc"><Users size={30}/></span><ArrowRight size={23}/><span className="avatar-disc"><Users size={30}/></span></div><div className="feature-copy"><small>02 / REFERRALS</small><h3>Your best customers.<br/>Your next customers.</h3></div></Reveal><Reveal className="brand-feature feature-retention"><img src={packageImage} alt="Packaging creating a reason to return" width="1024" height="1024" loading="lazy"/><div className="feature-copy"><small>03 / RETENTION</small><h3>A good reason<br/>to come back.</h3></div></Reveal></div></section>
<section className="section customer-section"><Reveal className="section-heading"><span className="eyebrow">FOR THE CUSTOMER</span><h2>And customers<br/>get something<br/><i>back.</i></h2><p>A brand experience that doesn’t stop at the doorstep. A little recognition. A little delight.</p><div className="customer-benefits">{['Rewards','Loyalty','Easy sharing','A better experience'].map(x=><span key={x}><Check size={12}/>{x}</span>)}</div></Reveal><Reveal className="customer-visual"><Phone/><RewardCard/></Reveal></section>
<section className="section" id="pricing"><Reveal className="pricing-heading"><span className="eyebrow">SMALL INVESTMENT. LASTING CONNECTIONS.</span><h2>Room for your<br/><i>next stage of growth.</i></h2><p>From your first hundred orders to your next thousand.</p></Reveal><div className="pricing-grid">{plans.map((plan,i)=><Reveal className={`pricing-plan ${i===1?'popular':''}`} key={plan.name}>{i===1&&<span className="popular-tag">MOST POPULAR</span>}<span className="plan-name">{plan.name.toUpperCase()}</span><div className="plan-price">₹{plan.price.toLocaleString('en-IN')}<span>/ month</span></div><p>{plan.description}</p><Button variant={i===1?'ivory':'default'} asChild><Link to="/start-free">Start Free Pilot <ArrowUpRight/></Link></Button></Reveal>)}</div><p className="pricing-note">Physical QR cards available separately.</p></section>
<section className="section setup"><div className="setup-heading"><div className="section-heading"><span className="eyebrow">FROM YOUR STORE TO THEIR DOOR</span><h2>Five steps.<br/><i>One new possibility.</i></h2></div><Button variant="link" asChild><Link to="/demo">Take it for a spin <ArrowUpRight/></Link></Button></div><div className="setup-steps">{[['CONNECT STORE','Start with your storefront.'],['CREATE CAMPAIGN','Choose what happens next.'],['GENERATE QR CARDS','Make the invitation yours.'],['INSERT INTO PACKAGES','A small addition to every order.'],['TRACK RESULTS','See the story come full circle.']].map(([title,text],i)=><Reveal className="setup-step" key={title}><span>0{i+1}</span><h4>{title}</h4><p>{text}</p></Reveal>)}</div></section>
<section className="final-cta"><span className="eyebrow">THERE’S MORE INSIDE.</span><h2>Your next customer<br/>might already be inside<br/><i>your last order.</i></h2><p>Turn every delivery into a measurable growth opportunity.</p><div className="final-actions"><Button variant="ivory" asChild><Link to="/start-free">Start Free Pilot <ArrowUpRight/></Link></Button><Button variant="lightOutline" asChild><Link to="/demo">Book a Demo <ArrowUpRight/></Link></Button></div><img src={packageImage} width="1024" height="1024" loading="lazy" alt="Your next opportunity inside an AVIRA package"/></section><Footer/></div>;}
